id: I3659B14B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:08:38+00:00'
last_modified: '2022-06-08T08:29:21.559741+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC360
  title: 'སྔགས་ཆས་ཀྱི་རྣམ་བཤད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4348':
      image_group_id: I2PD18326
      title: ''
      total_pages: 406
      order: 1
      base_file: 4348.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
